### ISSUE TITLE
Bot dofus

### ISSUE THREAD

**Issue by JacobPollF** [LucBerge/LucBerge#1]
Salut, j'ai regardé comment tu as fait ton bot et c'est très propre bravo à toi. Voulant moi même en coder un et bloquant sur la partie analyse  de paquets j'ai voulu m'inspirer du tien mais il est tellement bien découpé en modules que je n'arrive pas à voir où est-ce que tu traites la partie analyse des paquets.
Si tu pouvais m'éclairer sur où trouver les informations pour décoder les paquets ( sachant que j'ai les sources de dofus 2.3 ) ca serait sympa car c'est là où je bloque

**Comment by LucBerge** [comment]
Salut, merci pour ton commentaire.

Lorsque j'ai commencé l'analyse de trame, j'ai premièrement fait du reverse engineering pour pouvoir récupérer les infos qui m'intéressent. C'est super compliqué et ça me prennait beaucoup trop de temps pour un résultat médiocre. J'ai alors décider de créer le projet [bot4dofus/Datafus](https://github.com/bot4dofus/Datafus) pour extraire le code source et construire des fichiers "utiles" comme la structure des trames. Jette un oeil au fichier [data/events.json](https://github.com/bot4dofus/Datafus/tree/master/data) c'est exactement ce que tu recherches.

Attention, les id de chaque trame changent à chaque mise à jour, le fichier [data/ events.properties](https://github.com/bot4dofus/Datafus/tree/master/data) trace l'évolution des ids à chaque mise à jour.

La classe [NetworkMessage](https://github.com/bot4dofus/Datafus/blob/master/data/DofusInvoker/scripts/com/ankamagames/jerakine/network/NetworkMessage.as) est ce qui existe de plus haut et est un peu particulière. Elle est composé d'un header et d'un champ "taille" de taille variable.

Je compte refaire tout le système d'analyse de trame grace au projet Datafus mais je n'ai plus beaucoup de temps libre...

Tu codes ton bot en quoi ?
Quel est/sont les objectifs de ton bot ?

**Comment by JacobPollF** [comment]
Mon but pour l'instant c'est de faire un MITM. Je sniff et analyse les paquets en C et ensuite j'envoie les résultats en python pour effectuer les inputs. En fait, j'ai déjà un bot pixel qui peut farmer et se déplacer n'importe où sur la carte mais il ne peut pas combattre/vérifier si son inventaire est plein et c'est bête de faire ces fonctionnalités en traitement d'image, c'est pourquoi j'aimerais faire de l'analyse de paquets pour réaliser ces fonctionnalités.

Je viens de jeter un coup d'oeil sur events.json et en effet, il y a l'ID du type de message et des attributs. Cependant, j'ai un peu de mal à comprendre la construction global du paquet. Quelque part j'imagine qu'ils construisent la partie ethernet sur 14 bits, la partie IP sur à peu près 20 bits et ensuite la partie data qui m'intéresse. Mais je ne comprends pas comment ils construisent la partie data, j'ai en effet vu que dans la classe NetworkMessage il y avait la méthode writePacket dans lequel ils écrivent des octets/shorts mais je ne vois pas où dans la partie data sont écrit ces informations : au début du segment data, à la fin, au milieu ? Si tu pouvais m'éclairer, j'ai dû louper quelque chose

**Comment by LucBerge** [comment]
Du temps ou je faisais du reverse engineering, j'ai fait [une page wiki](https://github.com/bot4dofus/B4D/wiki/Support-new-socket-parsing) pour apprendre à parser les sockets. Cette page n'est pas à jour car j'ai fait Datafus plus tard et l'id de la trame utilisé dans l'exemple à changé depuis.

Tu n'as pas à te préocuper du packet ethernet, ni du packet ip. Trouve une library pour sniffer des pacet en C et focus sur la data.

Le nom de l'event parsé dans l'exemple est "ChatServerMessage". Tu peux utiliser events.json pour identifier l'id et les champs à récupérer.

La superclass de ChatServerMessage est ChatAbstractServerMessage qui a comme superclass NetworkMessage. L'ordre des champs est donc:
1. Champs de NetworkMessage
2. Champs de ChatAbstractServerMessage
3. Champs de ChatServerMessage

Tu verras que ça colle parfaitement avec la page wiki que j'avais fait. Mais je n'avais pas su identifier tous les champs

**Comment by LucBerge** [comment]
Avec plaisir, ça m'interresse de suivre le développement de ton bot oui
