### ISSUE TITLE
Message ID introuvable dans events.json

### ISSUE THREAD

**Issue by JacobPollF** [LucBerge/LucBerge#2]
Hey, me revoilà avec quelque update. Du coup j'ai avancé sur l'analyse de paquets et je me retrouve face à un problème, je ne trouve pas certains message ID dans le fichier events.json. Le contexte : Apres un changement de map, mon client envoie un message d'ID 8121 qui est un MapInformationsRequestMessage. Je recois après ca un message du serveur d'ID 15616 ( 0xF402 pour le header ) sauf que je ne trouve rien qui a pour ID 15616 dans le fichier. De même, il m'arrive de recevoir 0x0000 et il n'y a aucune entrée qui a pour ID 0 dans le fichier. D'ou vient le problème ?

**Comment by LucBerge** [comment]
Ah oui c'est étrange. Si le header est bien 0xF402, l'id est bien 15616.

Est ce que tu es sûr qu'il s'agit bien du header ? Tu peux envoyer un screen (wireshark ou autre) stp ?

**Comment by JacobPollF** [comment]
Ok, pour ce qui de l'ID 15616 c'est une erreur de ma part, j'avais mal compris comment étaient alloués en mémoire les paquets dans libpcap mais maintenant c'est réglé. Cependant, j'ai toujours des paquets avec des message ID de 0.  Voici une capture de la partie data. C'est un paquet provenant du serveur dofus, émis sur le port 5555 : 
![Capture d’écran 2023-01-01 à 23 22 31](https://user-images.githubusercontent.com/121199729/210186542-438eba86-576e-4a5e-8651-afc2eb73364b.png)


Aussi, si tu pouvais me dire comment décrypter les paquets venant du serveur et non du client car j'ai l'impression qu'ils ne sont pas construits de la même manière ?

**Comment by LucBerge** [comment]
J'ai fait ma petite recherche. Je reçois `MapComplementaryInformationsDataMessage` a chaque fois que je change de map.

> Cependant, j'ai toujours des paquets avec des message ID de 0.

Je reçois aussi des events avec header `0x00 0x00` alors que ce n'était pas le cas dans les versions précédentes. C'est comme si ils avaient ajouté une couche au dessus de `NetworkMessage` pour faire passer d'autres infos. Il va falloir chercher dans le code pour savoir de quoi il s'agit.

> Aussi, si tu pouvais me dire comment décrypter les paquets venant du serveur et non du client car j'ai l'impression qu'ils ne sont pas construits de la même manière ?

Oui, ils sont construit de la même manière.
Quel est l'event que tu veux parser ?

**Comment by JacobPollF** [comment]
Les évènements qu'ils me faudraient sont : 
-Les évènements relatifs au combat : position / nombre de PM, pour pouvoir faire les combats de façon automatisé

-Le nombre de pods restant  dans l'inventaire, pour pouvoir savoir quand aller à la banque

-Eventuellement les évènements liés à la banque

Ce qui est bizarre d'ailleurs avec l'inventaire c'est que on ne reçoit aucun paquet quand on l'ouvre, je me demande donc comment on récupère les infos liées à l'inventaire ?

Pour ce qui est de l'histoire du header 0x00 00, je vais chercher aussi. Mais comme ceux sont des paquets émis par le serveur, dans quelle dossier dois-je regarder puisque j'imagine que NetworkMessage.as ne construit les paquets que côté client

**Comment by LucBerge** [comment]
> Les évènements qu'ils me faudraient sont :
> - Les évènements relatifs au combat : position / nombre de PM, pour pouvoir faire les combats de façon automatisé
> - Le nombre de pods restant dans l'inventaire, pour pouvoir savoir quand aller à la banque
> - Eventuellement les évènements liés à la banque
> 
> Ce qui est bizarre d'ailleurs avec l'inventaire c'est que on ne reçoit aucun paquet quand on l'ouvre, je me demande donc comment on récupère les infos liées à l'inventaire ?

Je ne peux pas t'aider la dessus, je n'en sait pas plus. Bonne recherche ;)

> Pour ce qui est de l'histoire du header 0x00 00, je vais chercher aussi. Mais comme ceux sont des paquets émis par le serveur, dans quelle dossier dois-je regarder puisque j'imagine que NetworkMessage.as ne construit les paquets que côté client

Je n'ai aucune idée ou chercher. C'est peut être même pas accessible...

**Comment by JacobPollF** [comment]
J'espère que ca l'est, sinon je vais devoir passer sur dofus 1.29, aie
Merci quand meme pour l'aide :)

**Comment by LucBerge** [comment]
Les évents que tu cherches sont quelque part la dedans **c'est sur**: https://github.com/bot4dofus/Datafus/blob/master/data/events.json
Tu n'as pas besoin de passer sur Dofus 1.29.

Les header en 0x00 0x00 c'est autre chose. Tu n'en a pas besoin pour faire ce que tu souhaites. Ignore les simplement.

**Comment by LucBerge** [comment]
N'oublie pas de regarder le nouveau fichier [events.properties](https://github.com/bot4dofus/Datafus/blob/master/data/events.properties). Les IDs ont changé avec la dernière mise à jour.
