### ISSUE TITLE
Api requests

### ISSUE THREAD

**Issue by ernaqua** [LucBerge/LucBerge#3]
Hello just saw your work really good!
just wanna ask if there is an api request to retrieve kamas ammount on servers that would be cool thanks !:)
and what are Fragements?m really curious cuz I find it in the money api but can't find it anywhere else in the code
very good work :)

**Comment by LucBerge** [comment]
Hello, thank you for your interest.
Are you talking about B4D or Datafus ?
What do you mean by "retrieve kamas ammount on servers" ?

**Comment by ernaqua** [comment]
I am talking about Datafus, I mean by that if there an api to see the ammount of kamas on each server in the dofus account or something similar
